// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poesoabpzgdgvcuerptp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZXNvYWJwemdkZ3ZjdWVycHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjI0OTUsImV4cCI6MjA1OTQ5ODQ5NX0.96ldGo2J9iqr_Io_IdXyxBzQvsfTA00zvCu-emRrvY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);